const starNameMapping = {
    7588: { commonName: "Achernar", maoriName: null },
    60718: { commonName: "Acrux", maoriName: null },
    68702: { commonName: "Beta Centauri", maoriName: null },
    17702: { commonName: "Alcyone", maoriName: "Matariki" },
    21421: { commonName: "Aldebaran", maoriName: "Taumata Kuku" },
    109268: { commonName: "Alnair", maoriName: null },
    26311: { commonName: "Alnilam", maoriName: "Tautoru" },
    26727: { commonName: "Alnitak", maoriName: "Tautoru" },
    97649: { commonName: "Altair", maoriName: "Poutūterangi" },
    80763: { commonName: "Antares", maoriName: "Rehua" },
    71683: { commonName: "Alpha Centauri", maoriName: "Uruao"},
    71681: { commonName: "Alpha Centauri", maoriName: "Uruao"},
    25336: { commonName: "Bellatrix", maoriName: null },
    27989: { commonName: "Betelgeuse", maoriName: "Putara" },
    30438: { commonName: "Canopus", maoriName: "Autahi" },
    36850: { commonName: "Castor", maoriName: "Whakaahu" },
    61084: { commonName: "Gacrux", maoriName: "Whakaahu" },
    62434: { commonName: "Mimosa", maoriName: "Whakaahu" },
    37826: { commonName: "Pollux", maoriName: null },
    25930: { commonName: "Mintaka", maoriName: "Tautoru" },
    17851: { commonName: "Pleione", maoriName: "Matariki" },
    11767: { commonName: "Polaris", maoriName: null },
    70890: { commonName: "Proxima", maoriName: null },
    24436: { commonName: "Rigel", maoriName: "Puanga" },
  };